[package]
name = "fj-trace"
version = "0.1.0"
edition = "2024"

[dependencies]
fj-core = { path = "../fj-core" }
smallvec = { workspace = true }

[dev-dependencies]
fj-test-utils = { path = "../fj-test-utils" }
proptest = { workspace = true }
serde_json = "1.0.149"
