[package]
name = "fj-lax"
version = "0.1.0"
edition = "2024"

[dependencies]
fj-core = { path = "../fj-core" }

[dev-dependencies]
fj-test-utils = { path = "../fj-test-utils" }
proptest = { workspace = true }
criterion = "0.8"

[[bench]]
name = "lax_baseline"
harness = false
