[package]
name = "fj-ad"
version = "0.1.0"
edition = "2024"

[dependencies]
fj-core = { path = "../fj-core" }
fj-lax = { path = "../fj-lax" }
smallvec = { workspace = true }

[dev-dependencies]
fj-interpreters = { path = "../fj-interpreters" }
proptest = { workspace = true }
